// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRvtJQcbN0Ae-UluLrMQ24PdkWSzy1ys',
    appId: '1:947445061824:web:1f36c431933c2712f1f525',
    messagingSenderId: '947445061824',
    projectId: 'bms-mobile-794f5',
    authDomain: 'bms-mobile-794f5.firebaseapp.com',
    storageBucket: 'bms-mobile-794f5.firebasestorage.app',
    measurementId: 'G-GYK1J6EZ3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFCPMuOlhvWDJ4gCvSb8ZQNwNnK4n4mE',
    appId: '1:947445061824:android:16b3b093bca458b1f1f525',
    messagingSenderId: '947445061824',
    projectId: 'bms-mobile-794f5',
    storageBucket: 'bms-mobile-794f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtamDEsRHmZKp-m5ZPo06DRFwNjH-wOEA',
    appId: '1:947445061824:ios:520669d29428308ef1f525',
    messagingSenderId: '947445061824',
    projectId: 'bms-mobile-794f5',
    storageBucket: 'bms-mobile-794f5.firebasestorage.app',
    iosBundleId: 'com.example.bmsmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtamDEsRHmZKp-m5ZPo06DRFwNjH-wOEA',
    appId: '1:947445061824:ios:520669d29428308ef1f525',
    messagingSenderId: '947445061824',
    projectId: 'bms-mobile-794f5',
    storageBucket: 'bms-mobile-794f5.firebasestorage.app',
    iosBundleId: 'com.example.bmsmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBRvtJQcbN0Ae-UluLrMQ24PdkWSzy1ys',
    appId: '1:947445061824:web:d1caf57cd7ca788ff1f525',
    messagingSenderId: '947445061824',
    projectId: 'bms-mobile-794f5',
    authDomain: 'bms-mobile-794f5.firebaseapp.com',
    storageBucket: 'bms-mobile-794f5.firebasestorage.app',
    measurementId: 'G-QTDDFPY63P',
  );
}
